const choo = require('choo')

var app = choo()
app.use(require('./stores/dbs'))
app.use(require('./stores/profiles'))
app.use(require('./stores/posts'))
app.use(require('./stores/feed'))
app.use(require('./stores/header'))
app.use(require('./stores/gizmos'))
app.use(require('./stores/comments'))
app.use(require('./stores/find-friend'))
app.use(require('./stores/parallel'))

app.route('/', require('./views/main'))
app.route('/profile/:key', require('./views/profile'))
app.route('/profile/:key/follows', require('./views/follows'))
app.route('/profile/:key/edit', require('./views/profile'))
app.route('/post/*', require('./views/post'))
app.route('/settings', require('./views/settings'))

app.route('/workbench', require('./views/workbench'))
app.route('/shop/:key', require('./views/shop'))
app.route('/gizmos/:key', require('./views/subgizmos'))
app.route('/gizmo/*', require('./views/gizmo'))
app.route('/find-friend', require('./views/find-friend'))
app.route('/keys', require('./views/keys'))

app.mount('main')
